fixed error on no tracks
Allvaa/lavalink-musicbot pull request #147
Opened 2021-09-06 17:02 UTC by Tharki-God

was giving errors when no tracks so fixed that shit senpai

2021-09-07 01:08 UTC, Allvaa requested changes

2021-09-07 01:08 UTC, Allvaa commented on src/commands/play.js
> +               const result =  await music.load(util.isValidURL(query) ? query : `ytsearch:${query}`);
```suggestion
            const result =  await music.load(util.isValidURL(query) ? query : `ytsearch:${query}`);
```

2021-09-07 01:08 UTC, Allvaa commented on src/commands/play.js
> +            if (!result || !result.tracks.length)  return ctx.respond({
```suggestion
            if (!result?.tracks.length)  return ctx.respond({
```
use optional chaining

2021-09-07 01:08 UTC, Allvaa commented on src/commands/play.js
> +            const { type, playlistName, tracks } = result;
```suggestion
            const { type, playlistName, tracks } = result;
```

2021-09-09 01:58 UTC, Tharki-God commented
well did the changes :)

2021-09-09 02:03 UTC, Allvaa approved these changes
ok looks good, thanks

2021-09-09 02:04 UTC, merged