clears the queue
Allvaa/lavalink-musicbot pull request #89
Opened 2021-05-11 13:13 UTC by rajamoulimallareddy

2021-05-11 14:19 UTC, Allvaa requested changes

2021-05-11 14:19 UTC, Allvaa commented on src/commands/clearqueue.js
> +    aliases: ["clr","clear],
string isn't closed

2021-05-11 14:33 UTC, Allvaa requested changes

2021-05-11 14:33 UTC, Allvaa commented on src/commands/clearqueue.js
> +            music.queue.length = [];
assigning value to Array#length (.queue.length) doesn't change anything, also you can't assign to it because it's not writeable

2021-05-11 18:31 UTC, Allvaa commented
one question before i merge this.
isn't it supposed to clear all the queued tracks or it just keep the first queued track and clear the rest?

2021-05-12 16:56 UTC, rajamoulimallareddy commented
> one question before i merge this.
> isn't it supposed to clear all the queued tracks or it just keep the first queued track and clear the rest?

it keep first song in queue and remove rest of the queue
![image](https://user-images.githubusercontent.com/68652418/118014722-234f2d80-b371-11eb-98dc-eef6078d4aa1.png)

2021-05-12 18:27 UTC, Allvaa approved these changes
ok, thanks for the contribution!

2021-05-12 18:27 UTC, merged